### ISSUE TITLE
Duplication of element resources.repository.web - dzil test fails on clone

### ISSUE THREAD

**Issue by szabgab** [sdondley/Mojo-DOM-Role-Analyzer#1]
Hi, I cloned the repository installed all the dependencies and I got this strange error. Any idea why is that?

```
$ dzil test

[DZ] building distribution under .build/5CJ4cp4KZV for installation
[DZ] beginning to build Mojo-DOM-Role-Analyzer
[Git::NextVersion] Bumping version from 0.010 to 0.011
[PodVersion] couldn't find '=head1 NAME' in lib/Mojo/DOM/Role/Analyzer.pm, not adding '=head1 VERSION'
[DZ] guessing dist's main_module is lib/Mojo/DOM/Role/Analyzer.pm
[GitHub::Meta] Getting GitHub repository info
Duplication of element resources.repository.web at /home/gabor/perl5/lib/perl5/Dist/Zilla.pm line 595.
```

**Comment by sdondley** [comment]
No, sorry, I've never seen anything like that before. I only know enough Dist::Zilla to be dangerous. I'll look into it, though. It sounds like it has something to do with github, though, as if it's trying to upload to github but it found something there already? My Dist::Zilla config has a module to automatically post to github.

**Comment by szabgab** [comment]
I think it was trying to configure the content of the META files, but don't know anything about Dist::Zilla

**Comment by sdondley** [comment]
Someone has pointed out that the dist.ini file has the Repository module and GitHub::Meta modules which may overlap. I'll try to fix up when I get a chance.

**Comment by sdondley** [comment]
I tried duplicating the issue on another machine but was not able to. Can you please try upgrading the https://metacpan.org/pod/Dist::Zilla::Plugin::Repository and https://metacpan.org/pod/Dist::Zilla::Plugin::GitHub::Meta modules and see if you get lucky?

**Comment by szabgab** [comment]
I think they are the latest:

```
$ cpanm Dist::Zilla::Plugin::Repository
Dist::Zilla::Plugin::Repository is up to date. (0.24)
$ cpanm Dist::Zilla::Plugin::GitHub::Meta 
Dist::Zilla::Plugin::GitHub::Meta is up to date. (0.47)
```

BTW I just tried and if I comment out either `[Repository]` or `[GitHub::Meta]` the problem goes away.

If I remove `[Repository]` it still adds the 'resources' to META.json as I think you wanted. I think tthe difference is that GitHub::Meta also adds the bugtracker while Repository only adds the repository entries.

**Comment by sdondley** [comment]
Ok thanks. I’ll see if I can just remove the first one.  I set these up a while ago and have forgotten the details. I’d be interested to know why I don’t see the same error. Thanks for alerting me to this and helping me track it down.

**Comment by sdondley** [comment]
The [Repository] plugin has been commented out of the dist.ini file in the latest release.

**Comment by sdondley** [comment]
Close

**Comment by szabgab** [comment]
Thanks
