### ISSUE TITLE
t/02-common.t fails with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [sdondley/Mojo-DOM-Role-Analyzer#5]
Using a perl compiled with increased floating point accuracy (config option -Duselongdouble) the test suite fails:
```
#   Failed test 'gets c orrect tag analysis result'
#   at t/02-common.t line 83.
#     Structures begin differing at:
#          $got->[0]{avg_tag_depth} = '3.66666666666666667'
#     $expected->[0]{avg_tag_depth} = '3.66666666666667'
# Looks like you failed 1 test of 8.
t/02-common.t .. 
```

(At least it does on a freebsd12 system, did not check on a similarly configured linux system)

**Comment by sdondley** [comment]
Thanks for the report. Should be fixed now.
